# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example.infra.tf-config
  namespace: default
data:
  main.tf: |
    provider "aws" {
      access_key = var.ACCESS_KEY_ID
      secret_key = var.SECRET_ACCESS_KEY
      region     = "eu-central-1"
    }

    resource "aws_route53_record" "www" {
      zone_id = "Z3ABCDE5FGHIJK"
      name    = "subdomain.example.com"
      ttl     = "120"
      type    = "A"
      records = ["1.2.3.4"]
    }
  variables.tf: |
    variable "ACCESS_KEY_ID" {
      description = "AWS Access Key ID of technical user"
      type        = string
    }

    variable "SECRET_ACCESS_KEY" {
      description = "AWS Secret Access Key of technical user"
      type        = string
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: example.infra.tf-vars
  namespace: default
type: Opaque
stringData:
  terraform.tfvars: |
    ACCESS_KEY_ID = "AAAAAAAAAAAAAAAAAAAA"
    SECRET_ACCESS_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
